### ISSUE TITLE
Does not work for me on www.amazon.sg

### ISSUE THREAD

**Issue by chjohans** [pip8786/CCNA#19]
Thanks for making this, I was very excited to find this as the issue with Amazon not allowing us to set a nickname for each credit card has been bugging me for years!

This works just fine for me on https://www.amazon.com/cpe/yourpayments/wallet, when I click on the extension I get the "Cards and nicknames" dialogue and I can enter a nickname for each card in my account.

But it does not work on https://www.amazon.sg/cpe/yourpayments/wallet, when I click on the extension I just get a messagebox that says "This is an Amazon wallet tab". Same thing happens on the checkout page, when I click the extenstion it again says "This is an Amazon wallet tab", but I don't get the dialogue to assign nicknames.

This is of limited use to me as my primary Amazon site is amazon.sg.

Since your extention chrome store page says "Now for any country" I assume you would like to have a go at fixing this?

Oh and the issue with a credit card being listed twice in the nickname dialogue I believe happens because the extention picks up your "Default" payment method twice, since it will be listed twice on the wallet page. If I enter a nickname for both duplicate cards in the nickname dialogue the result is that that card shows the nickname twice. TRhis is a minor issue tho, main thing is to get this to work on amazon.sg

**Comment by pip8786** [comment]
@chjohans are you able to help debug this a bit? The .sg domain is included in the manifest, and clearly the extension is loading up for you, but just not finding the credit cards on the page. If you have experience looking at HTML structure and willing to look around, let me know and I can tell you what to look for. 

Thanks for the tip on fixing the double card issue listed in #18 .

**Comment by pip8786** [comment]
The line for .sg in the manifest: https://github.com/pip8786/CCNA/blob/master/extension/manifest.json#L74

**Comment by chjohans** [comment]
Thanks @pip8786 for your lightning-fast response. Just let me know what you need and I'll try my best to help debug this.

**Comment by pip8786** [comment]
@chjohans If you're using chrome, could you go to the wallet URL you listed above, open developer tools/console (easiest way to do that is click anywhere on the page and hit inspect), then in the console type: `$$(".pmts-instrument-number-tail")`. That will do the same CSS selector my extension uses to find the credit card displays on the page. If it's working as expected, you should see a result per credit card you have saved. I've done it on mine as an example:

<img width="695" alt="Screenshot 2023-12-15 at 3 41 03 PM" src="https://github.com/pip8786/CCNA/assets/1085106/f95a5691-b5c7-44d8-871b-f9eb78afd2e8">

If that works, then we may be having another issue. If it doesn't I'll explain how to send me the selector for your version of the site (or I'll sign up for an account on that version, but that gets more complicated since I may not have a credit card that can be saved on that version). 

You can test it on the  *.com one too to see it working on that page since you say that one is OK.

**Comment by chjohans** [comment]
This is the output when on https://www.amazon.com/cpe/yourpayments/wallet where I do see the nicknames for each of my credit cards:
![snap003865](https://github.com/pip8786/CCNA/assets/24390228/b140be59-fa80-4140-964a-b124d06a978f)

This is the output when on https://www.amazon.sg/cpe/yourpayments/wallet where I do NOT see the nicknames for each of my credit cards:
![snap003866](https://github.com/pip8786/CCNA/assets/24390228/67a47c94-d4a1-4fc6-b6d6-c53d2a2651d1)

Got 3 credit cards on both sites, actually it's the same account and same 3 credit cards. I see the nickname twice of my "preferred payment method" which is listed twice. Of course only on amazon.com, on amazon.sg I don't see the nicknames at all.

**Comment by pip8786** [comment]
Well that's interesting. Seems like the HTML structure is the same. I will have to sign up for an account on that version of amazon and test it out. Thanks for looking into it, I will try to get to it this week!

**Comment by pip8786** [comment]
Update for this is submitted for review. It should be published soon and then available to you as 1.0.12. I've updated a lot of other things as well, please let me know how it works.

**Comment by pip8786** [comment]
Btw I noticed that in the manifest I had the Singapore domain wrong (.com.sg instead of .sg) and that was the main reason it was broken. This lead me to updating a bunch of stuff though so it was worth working through those issues. Thanks for all the help debugging!

**Comment by chjohans** [comment]
Thanks again for making this, and for fixing the issue with amazon.sg as well as the duplicate nickname for the "default payment method". It works great now!
